<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DQ-Harish" ignored="2" name="Default test" tests="1" failures="0" timestamp="08 Nov 2017 07:34:48 GMT" time="0.093" errors="0">
  <testcase name="@BeforeClass beforeConfig" time="0.062" classname="assure.scripts.SmokeTest">
    <failure type="java.lang.ExceptionInInitializerError">
      <![CDATA[java.lang.ExceptionInInitializerError
	at assure.scripts.SmokeTest.beforeConfig(SmokeTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:165)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
	at assure.pages.Home_Pages.<clinit>(Home_Pages.java:13)
	... 26 more
]]>
    </failure>
  </testcase> <!-- @BeforeClass beforeConfig -->
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="assure.scripts.SmokeTest">
    <skipped/>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="createTestrun" time="0.0" classname="assure.scripts.SmokeTest">
    <skipped/>
  </testcase> <!-- createTestrun -->
  <testcase name="createTestCase" time="0.0" classname="assure.scripts.SmokeTest">
    <ignored/>
  </testcase> <!-- createTestCase -->
  <testcase name="createSmokeuser" time="0.0" classname="assure.scripts.SmokeTest">
    <ignored/>
  </testcase> <!-- createSmokeuser -->
</testsuite> <!-- Default test -->
